name: Code Quality Report

on:
  push:
    branches:
      - main

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install ESLint and Prettier temporarily
        run: |
          npm init -y
          npm install --save-dev eslint prettier @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint-config-prettier eslint-plugin-prettier

      - name: Run ESLint (only show issues, don't fail)
        run: |
          echo "📌 ESLint Report"
          npx eslint . --ext .ts --no-eslintrc \
            --parser=@typescript-eslint/parser \
            --plugin=@typescript-eslint \
            --plugin=prettier \
            --rule "prettier/prettier:warn" || true

      - name: Run Prettier Check (only show issues, don't fail)
        run: |
          echo "📌 Prettier Report"
          npx prettier . --check "**/*.ts" || true
