name: Code Review

on:
  push:
    branches: [ "main" ]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Run Prettier Check
        run: npm run format:check
        continue-on-error: true

      - name: Run npm Audit
        run: npm run audit
        continue-on-error: true

      - name: Run Snyk Scan
        run: npx snyk test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Run Snyk Scan
        run: |
          npx snyk test --severity-threshold=low | tee snyk-report.txt
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      # Upload reports as artifacts
      - name: Upload Reports as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: code-review-reports
          path: |
            snyk-report.txt
