name: Code Quality Report

on:
  push:
    branches:
      - main

jobs:
  lint-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install ESLint and Prettier temporarily
        run: |
          npm init -y
          npm install --save-dev eslint@9.3.0 prettier @typescript-eslint/parser @typescript-eslint/eslint-plugin eslint-plugin-prettier eslint-config-prettier

      - name: Create temporary ESLint config (.mjs format)
        run: |
          echo "export default {
            files: ['**/*.ts'],
            languageOptions: {
              parser: '@typescript-eslint/parser',
              parserOptions: { ecmaVersion: 'latest', sourceType: 'module' }
            },
            plugins: {
              '@typescript-eslint': require('@typescript-eslint/eslint-plugin')
            },
            rules: {
              '@typescript-eslint/no-unused-vars': 'warn',
              'prettier/prettier': 'warn'
            }
          };" > eslint.config.mjs

      - name: Run ESLint (show issues, don’t fail build)
        run: |
          echo "📌 ESLint Report"
          npx eslint . --config eslint.config.mjs || true

      - name: Run Prettier Check (show issues, don’t fail build)
        run: |
          echo "📌 Prettier Report"
          npx prettier . --check "**/*.ts" || true
