name: Code Review

on:
  push:
    branches:
      - main

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint (no auto-fix)
        run: npm run lint

      - name: Check code formatting with Prettier
        run: npm run format:check

      - name: Check for vulnerabilities (npm audit)
        run: npm audit --audit-level=high

      - name: Run Snyk Scan
        uses: snyk/actions/node@v1
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
